### ISSUE TITLE
PARIInterface

### ISSUE THREAD

**Issue by videlec** [gap-packages/alnuth#16]
Thanks to Markus and Bill we now have a direct C interface to PARI (the library), see [PARIInterface](https://github.com/gap-packages/PARIInterface). It is infinitely faster and more reliable than going through writing files and executing them via gp. I believe that we should find a way to slowly make Alnuth use PARIInterface (and possibly merge them).

**Comment by fingolfin** [comment]
As soon as you have a version of the package that actually works reliably and is distributed with GAP, we can certainly look into this :-).

**Comment by fingolfin** [comment]
Considering that the development of PARIInterface has stopped a month after this PR has opened, I don't think there's anything to act on here :-(.
