### ISSUE TITLE
MaximalOrderByUnitsPcpGroup

### ISSUE THREAD

**Issue by CarmineMonetta** [gap-packages/alnuth#23]
This is the message I am getting when I run this piece of code. Is there a quick fix?
Thank you in advance!!!

gap> x:=Indeterminate(Integers, "x");
x
gap> MaximalOrderByUnitsPcpGroup(x^2+1);
  ***   at top-level: un=lift(bnf.tufu)
  ***                             ^-----
  ***   not a function in function call
  ***   at top-level: ...or(i=1,#un,print(p2v(n,un[i]),","))
  ***                                             ^----------
  ***   incorrect type in _[_] OCcompo1 [not a vector] (t_POL).
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `GroupByGenerators' on 1 arguments called from
GroupByGenerators( gen 
 ) at /Applications/gap4r8/pkg/alnuth-3.1.0/gap/field.gi:152 called from
UnitGroupOfNumberField( F 
 ) at /Applications/gap4r8/pkg/alnuth-3.1.0/gap/field.gi:165 called from
UnitGroup( F 
 ) at /Applications/gap4r8/pkg/polycyclic-2.11/gap/exam/generic.gi:200 called \
from
<function "MaximalOrderByUnitsPcpGroup">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue

**Comment by fingolfin** [comment]
Based on the path of your GAP installation, you are using GAP 4.8, which is looooong out of support. Try updating to a newer version (4.12 was just released Friday)
